name: Unit Tests
on: [push, pull_request_target]

jobs:
  test:
    name: Test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9, "3.10-dev"]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2.1.4
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install -U setuptools

      - run: pip install -r requirements.txt

      - run: pip install -e .[dev]

      - run: pytest